[tox]
envlist = py38,py39,py310,py311,py312,py313,py314,lint

[testenv]
extras =
    test
    plot
commands =
    pytest {posargs}

[testenv:lint]
skip_install = True
deps = ruff
commands =
    ruff check .
    ruff format --check .
