[tox]
requires = tox>=4.22
envlist = py311,py312,py313,py314,lint

[testenv]
extras = plot
dependency_groups = test
commands =
    pytest {posargs}

[testenv:lint]
skip_install = True
dependency_groups = lint
commands =
    ruff check .
    ruff format --check .
