[tox]
envlist = py38,py39,py310,py311,py312,py313,py314,lint

[testenv]
extras =
    test
    plot
commands =
    pytest {posargs}

[testenv:lint]
basepython = python3
ignore_errors = True
extras =
    lint
commands =
     pylint ace
     pydocstyle ace
